[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient
    bogde/HX711
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    paulstoffregen/OneWire
    milesburton/DallasTemperature
